/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'title' : string,
  'content' : string,
  'date' : bigint,
  'author' : string,
  'category' : string,
}
export interface Message {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Program {
  'kind' : string,
  'name' : string,
  'description' : string,
}
export interface SiteSettings {
  'orgName' : string,
  'tagline' : string,
  'headerCtaText' : string,
  'twitterUrl' : string,
  'instagramUrl' : string,
  'email' : string,
  'headerSubtitle' : string,
  'address' : string,
  'phone' : string,
  'youtubeUrl' : string,
  'facebookUrl' : string,
  'footerNote' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'status' : string,
  'city' : string,
  'name' : string,
  'email' : string,
  'motivation' : string,
  'phone' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArticle' : ActorMethod<
    [string, string, string, bigint, string],
    undefined
  >,
  'addProgram' : ActorMethod<[string, string, string], undefined>,
  'approveVolunteer' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteArticle' : ActorMethod<[string], undefined>,
  'deleteProgram' : ActorMethod<[string], undefined>,
  'deleteVolunteer' : ActorMethod<[string], undefined>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getArticlesByCategory' : ActorMethod<[string], Array<Article>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getPrograms' : ActorMethod<[], Array<Program>>,
  'getProgramsByKind' : ActorMethod<[string], Array<Program>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'getVolunteersByStatus' : ActorMethod<[string], Array<Volunteer>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerVolunteer' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'rejectVolunteer' : ActorMethod<[string], undefined>,
  'sendMessage' : ActorMethod<[string, string, string, bigint], undefined>,
  'updateArticle' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateProgram' : ActorMethod<[string, string, string, string], undefined>,
  'updateSiteSettings' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];