/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'tanggal' : IDL.Int,
  'tipe' : IDL.Text,
  'judul' : IDL.Text,
  'deskripsi' : IDL.Text,
});
export const Location = IDL.Record({
  'id' : IDL.Text,
  'latitude' : IDL.Float64,
  'provinsi' : IDL.Text,
  'alamat' : IDL.Text,
  'kota' : IDL.Text,
  'nama' : IDL.Text,
  'tanggalKegiatan' : IDL.Text,
  'longitude' : IDL.Float64,
  'keterangan' : IDL.Text,
  'jumlahPeserta' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Article = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Int,
  'author' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Message = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Program = IDL.Record({
  'kind' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'orgName' : IDL.Text,
  'tagline' : IDL.Text,
  'headerCtaText' : IDL.Text,
  'twitterUrl' : IDL.Text,
  'instagramUrl' : IDL.Text,
  'email' : IDL.Text,
  'headerSubtitle' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'youtubeUrl' : IDL.Text,
  'facebookUrl' : IDL.Text,
  'footerNote' : IDL.Text,
});
export const Volunteer = IDL.Record({
  'status' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'motivation' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'addGalleryItem' : IDL.Func([GalleryItem], [], []),
  'addLocation' : IDL.Func([Location], [], []),
  'addProgram' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'approveVolunteer' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteArticle' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
  'deleteLocation' : IDL.Func([IDL.Text], [], []),
  'deleteProgram' : IDL.Func([IDL.Text], [], []),
  'deleteVolunteer' : IDL.Func([IDL.Text], [], []),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticlesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
  'getProgramsByKind' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'getVolunteersByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Volunteer)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerVolunteer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'rejectVolunteer' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
  'updateArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateProgram' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateSiteSettings' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'tanggal' : IDL.Int,
    'tipe' : IDL.Text,
    'judul' : IDL.Text,
    'deskripsi' : IDL.Text,
  });
  const Location = IDL.Record({
    'id' : IDL.Text,
    'latitude' : IDL.Float64,
    'provinsi' : IDL.Text,
    'alamat' : IDL.Text,
    'kota' : IDL.Text,
    'nama' : IDL.Text,
    'tanggalKegiatan' : IDL.Text,
    'longitude' : IDL.Float64,
    'keterangan' : IDL.Text,
    'jumlahPeserta' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Article = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Int,
    'author' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Message = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Program = IDL.Record({
    'kind' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const SiteSettings = IDL.Record({
    'orgName' : IDL.Text,
    'tagline' : IDL.Text,
    'headerCtaText' : IDL.Text,
    'twitterUrl' : IDL.Text,
    'instagramUrl' : IDL.Text,
    'email' : IDL.Text,
    'headerSubtitle' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'youtubeUrl' : IDL.Text,
    'facebookUrl' : IDL.Text,
    'footerNote' : IDL.Text,
  });
  const Volunteer = IDL.Record({
    'status' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'motivation' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'addGalleryItem' : IDL.Func([GalleryItem], [], []),
    'addLocation' : IDL.Func([Location], [], []),
    'addProgram' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'approveVolunteer' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteArticle' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
    'deleteLocation' : IDL.Func([IDL.Text], [], []),
    'deleteProgram' : IDL.Func([IDL.Text], [], []),
    'deleteVolunteer' : IDL.Func([IDL.Text], [], []),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
    'getProgramsByKind' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'getVolunteersByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Volunteer)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerVolunteer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'rejectVolunteer' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
    'updateArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProgram' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSiteSettings' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };